name: status

on: [push]

jobs:

  lint-test:

    runs-on: ubuntu-latest

    container:
      image: analysiscenter1/ds-py3:latest

    steps:
    - name: Update git
      run: |
        apt install ca-certificates
        add-apt-repository -y ppa:git-core/ppa
        apt update
        apt install git -y

    - name: Checkout SeismicPro
      uses: actions/checkout@v2
      with:
        submodules: true

    - name: Update pylint
      run: pip3 install -U pylint

    - name: Check pylint
      run: pylint -rn --rcfile pylintrc seismicpro

    - name: Run tests
      if: always()
      run: pytest -m "not slow" --disable-pytest-warnings -v seismicpro/src/tests
