name: Test installation

on:
  pull_request:
    branches:
    - master

jobs:

# -----------------------------------------
#    Use a module from local source
# -----------------------------------------
  use_as_local_module:

    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest] #, macos-latest, windows-latest]
        python-version: [3.6] #, 3.7, 3.8, 3.9]

    runs-on: ${{ matrix.os }}

    steps:
    - uses: actions/checkout@v2
      with:
        submodules: true
        lfs: true

    - name: Set up Python ${{ matrix.python-version }} on ${{ matrix.os }}
      uses: actions/setup-python@v2
      with:
        python-version: ${{ matrix.python-version }}

    - name: Install requirements
      run: |
        pip install --user -U pip
        pip install --user -r requirements.txt

    - name: Install batchflow requirements
      run: pip install --user -r seismicpro/batchflow/requirements.txt

    - name: Run 'import seismicpro'
      run: python -c 'import seismicpro'

    - name: Run basic tests
      run: |
        pip install -U pytest
        pytest  -m "not slow" --disable-pytest-warnings -v seismicpro/src/tests/dump_merge_test.py


# -----------------------------------------
#    Install with pip
# -----------------------------------------
  install_with_pip:

    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest] #, macos-latest, windows-latest]
        python-version: [3.6] #, 3.7, 3.8, 3.9]

    runs-on: ${{ matrix.os }}

    steps:
    - name: Set up Python ${{ matrix.python-version }} on ${{ matrix.os }}
      uses: actions/setup-python@v2
      with:
        python-version: ${{ matrix.python-version }}

    - name: Install with pip
      run: |
        pip install --user -U pip
        pip install wheel
        pip install --user git+https://github.com/${{ github.event.pull_request.head.repo.full_name }}.git@${{ github.head_ref }}#egg=SeismicPro

    - name: Run 'import seismicpro'
      run: python -c 'import seismicpro'

    - uses: actions/checkout@v2
      with:
#         submodules: true
        lfs: true

    - name: Run basic tests
      run: |
        pip install -U pytest
        pytest -m "not slow" --disable-pytest-warnings -v seismicpro/src/tests/dump_merge_test.py


# -----------------------------------------
#    Install with pipenv
# -----------------------------------------
  install_with_pipenv:

    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest] #, macos-latest, windows-latest]
        python-version: [3.6] #, 3.7, 3.8, 3.9]

    runs-on: ${{ matrix.os }}

    steps:
    - name: Set up Python ${{ matrix.python-version }} on ${{ matrix.os }}
      uses: actions/setup-python@v2
      with:
        python-version: ${{ matrix.python-version }}

    - name: Install with pipenv
      run: |
        pip install --user -U pip
        pip install wheel pipenv
        pipenv --python ${{ matrix.python-version }}
        pipenv install git+https://github.com/${{ github.event.pull_request.head.repo.full_name }}.git@${{ github.head_ref }}#egg=SeismicPro

    - name: Run 'import seismicpro' in installed environment
      run: pipenv run python -c 'import seismicpro'

    - uses: actions/checkout@v2
      with:
        lfs: true

    - name: Run basic tests
      run: |
        pipenv install pytest
        pipenv run python -m pytest --disable-pytest-warnings -v seismicpro/src/tests/dump_merge_test.py
